export const USER_SIGNIN_API = 'USER_SIGNIN_API'

export const USER_SIGNUP_API = 'USER_SIGNUP_API'

export const USlOGIN = 'USLOGIN'

export const GET_ALL_PROJECT_CATEGORY_SAGA = 'GET_ALL_PROJECT_CATEGORY_SAGA'

export const GET_ALL_PROJECT_CATEGORY = 'GET_ALL_PROJECT_CATEGORY'

export const CREATE_PROJECT_SAGA = 'CREATE_PROJECT_SAGA'

export const GET_LIST_PROJECT_SAGA = 'GET_LIST_PROJECT_SAGA'

export const UPDATE_PROJECT_SAGA = 'UPDATE_PROJECT_SAGA'

export const DELETE_PROJECT_SAGA = 'DELETE_PROJECT_SAGA'

export const GET_USER_API = 'GET_USER_API'

export const GET_USER_SEARCH = 'GET_USER'

export const GET_ALL_USER = 'GET_ALL_USER'

export const GET_ALL_USER_SAGA = 'GET_ALL_USER_SAGA'

export const ASSIGN_USER_API = 'ASSIGN_USER_API'

export const DELETE_USER_API = 'DELETE_USER_API'

export const DELETE_USER_SAGA = 'DELETE_USER_SAGA'

export const GET_PROJECT_DETAIL = 'GET_PROJECT_DETAIL'

export const GET_ALL_PROJECT_SAGA = 'GET_ALL_PROJECT_SAGA'

export const GET_USER_BY_PROJECT_ID_SAGA = 'GET_USER_BY_PROJECT_ID_SAGA'

export const GET_USER_BY_PROJECT_ID = 'GET_USER_BY_PROJECT_ID'

export const EDIT_USER = 'EDIT_USER'

export const EDIT_USER_SAGA = 'EDIT_USER_SAGA'